### ISSUE TITLE
PagedListView bounce back after loaded next page

### ISSUE THREAD

**Issue by cpunion** [szotp/async_controller#1]
When `fetchPage` finishes fast, the PageListView will bounce back.

Workaround: Add `await Future.delayed(Duration(milliseconds: 350))` in my overrided`fetchPage(int pageIndex)`

**Comment by cpunion** [comment]
Reproduce in example/lib/paged_loading_simple.dart:

```dart
class _SimpleController extends PagedAsyncController<int> {
  _SimpleController() : super(10);

  @override
  Future<PagedData<int>> fetchPage(int pageIndex) async {
    await Future<dynamic>.delayed(Duration(milliseconds: 150)); //<----- delay

    return PagedData(
      pageIndex,
      100000,
      List.generate(pageSize, (i) => i + pageIndex * pageSize),
    );
  }
}

```

**Comment by szotp** [comment]
Sorry for delay. I rewrote PagedAsyncController to load more items than visible (configurable through loadingMargin parameter). This should take care of this problem.
